
lang: en-US
title: Rajesh Kumar
email: kr.rajesh.phy@gmail.com
description: Theoretical Physicst
baseurl: "/research" # the optional subpath of your site, e.g. "/blog"
url:  # the base hostname & protocol for your site e.g. ""
PAPERS-ORG: "" #For online it shold be blank ""
author:
  name: Rajesh Kumar
  twitter:
  picture:
twitter_username:
github_username: 
logo: /assets/icons/logo.png # path of site logo, e.g. "/assets/images/logo.png"
search:  true # false (default)
search_full_content: true # true, false (default)
search_provider: lunr # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: https://rajeshphy.github.io/

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
